# Generated by Django 5.1.7 on 2025-03-31 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена: ')),
                ('have', models.BooleanField(default=True, verbose_name='v nalichii')),
                ('description', models.TextField()),
                ('video', models.ImageField(blank=True, null=True, upload_to='product_videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_photos/')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineshop.category')),
            ],
        ),
    ]
